//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeHotelaria
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumo
    {
        public int consumoCodigo { get; set; }
        public double valorUnitario { get; set; }
        public int quantidade { get; set; }
        public int hospCodigo { get; set; }
        public int prodCodigo { get; set; }
    
        public virtual hospedagem hospedagem { get; set; }
        public virtual produto produto { get; set; }
    }
}
