//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeHotelaria
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cidade> cidades { get; set; }
        public virtual DbSet<consumo> consumoes { get; set; }
        public virtual DbSet<estado> estadoes { get; set; }
        public virtual DbSet<funcionario> funcionarios { get; set; }
        public virtual DbSet<hospedagem> hospedagems { get; set; }
        public virtual DbSet<hospede> hospedes { get; set; }
        public virtual DbSet<pagamento> pagamentoes { get; set; }
        public virtual DbSet<produto> produtoes { get; set; }
        public virtual DbSet<quarto> quartos { get; set; }
        public virtual DbSet<reserva> reservas { get; set; }
        public virtual DbSet<servico> servicoes { get; set; }
        public virtual DbSet<servicosPrestado> servicosPrestados { get; set; }
        public virtual DbSet<tipoPagamento> tipoPagamentoes { get; set; }
        public virtual DbSet<tipoProduto> tipoProdutoes { get; set; }
        public virtual DbSet<tipoServico> tipoServicoes { get; set; }
        public virtual DbSet<unidadeProduto> unidadeProdutoes { get; set; }
    }
}
