//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeHotelaria
{
    using System;
    using System.Collections.Generic;
    
    public partial class funcionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public funcionario()
        {
            this.reserva = new HashSet<reserva>();
            this.hospedagem = new HashSet<hospedagem>();
        }
    
        public int funcCodigo { get; set; }
        public string funcNome { get; set; }
        public string funcCpf { get; set; }
        public string funcTelefone { get; set; }
        public string funcCelular { get; set; }
        public string funcLogradouro { get; set; }
        public int funcNumero { get; set; }
        public string funcBairro { get; set; }
        public string funcCep { get; set; }
        public string funcComplemento { get; set; }
        public int cidadeCodigo { get; set; }
        public Nullable<double> funcSalario { get; set; }
        public string funcLogin { get; set; }
        public string funcSenha { get; set; }
        public string funcStatus { get; set; }
    
        public virtual cidade cidade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reserva> reserva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hospedagem> hospedagem { get; set; }
    }
}
