//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeHotelaria
{
    using System;
    using System.Collections.Generic;
    
    public partial class hospede
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hospede()
        {
            this.hospedagem = new HashSet<hospedagem>();
            this.reserva = new HashSet<reserva>();
        }
    
        public int hospCodigo { get; set; }
        public string hospNome { get; set; }
        public string hospCpf { get; set; }
        public string hospTelefone { get; set; }
        public string hospCelular { get; set; }
        public string hospLogradouro { get; set; }
        public string hospNumero { get; set; }
        public string hospBairro { get; set; }
        public string hospCep { get; set; }
        public string hospComplemento { get; set; }
        public int cidadeCodigo { get; set; }
    
        public virtual cidade cidade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hospedagem> hospedagem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reserva> reserva { get; set; }
    }
}
