//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeHotelaria
{
    using System;
    using System.Collections.Generic;
    
    public partial class hospedagem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hospedagem()
        {
            this.consumoes = new HashSet<consumo>();
            this.pagamentoes = new HashSet<pagamento>();
            this.servicosPrestados = new HashSet<servicosPrestado>();
        }
    
        public int hospedagemCodigo { get; set; }
        public System.DateTime hospCheckin { get; set; }
        public System.DateTime hospCheckout { get; set; }
        public int funcCodigo { get; set; }
        public Nullable<int> reservaCodigo { get; set; }
        public int hospCodigo { get; set; }
        public int quartoCodigo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<consumo> consumoes { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual hospede hospede { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pagamento> pagamentoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<servicosPrestado> servicosPrestados { get; set; }
        public virtual quarto quarto { get; set; }
        public virtual reserva reserva { get; set; }
    }
}
