//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeHotelaria
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cidade> cidade { get; set; }
        public virtual DbSet<consumo> consumo { get; set; }
        public virtual DbSet<estado> estado { get; set; }
        public virtual DbSet<funcionario> funcionario { get; set; }
        public virtual DbSet<hospedagem> hospedagem { get; set; }
        public virtual DbSet<hospede> hospede { get; set; }
        public virtual DbSet<pagamento> pagamento { get; set; }
        public virtual DbSet<produto> produto { get; set; }
        public virtual DbSet<quarto> quarto { get; set; }
        public virtual DbSet<reserva> reserva { get; set; }
        public virtual DbSet<servico> servico { get; set; }
        public virtual DbSet<servicosPrestados> servicosPrestados { get; set; }
        public virtual DbSet<tipoPagamento> tipoPagamento { get; set; }
        public virtual DbSet<tipoProduto> tipoProduto { get; set; }
        public virtual DbSet<tipoServico> tipoServico { get; set; }
        public virtual DbSet<unidadeProduto> unidadeProduto { get; set; }
    }
}
