//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeHotelaria
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public produto()
        {
            this.consumo = new HashSet<consumo>();
        }
    
        public int prodCodigo { get; set; }
        public string prodDescricao { get; set; }
        public Nullable<decimal> prodValor { get; set; }
        public int tipoCodigo { get; set; }
        public int unidadeCodigo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<consumo> consumo { get; set; }
        public virtual tipoProduto tipoProduto { get; set; }
        public virtual unidadeProduto unidadeProduto { get; set; }
    }
}
