//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeHotelaria
{
    using System;
    using System.Collections.Generic;
    
    public partial class quarto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public quarto()
        {
            this.hospedagems = new HashSet<hospedagem>();
            this.reservas = new HashSet<reserva>();
        }
    
        public int quartoCodigo { get; set; }
        public string quartoDescricao { get; set; }
        public int quartoNumero { get; set; }
        public Nullable<int> quartoAndar { get; set; }
        public int quartoQtdPessoas { get; set; }
        public string quartoRamal { get; set; }
        public string quartoObservacao { get; set; }
        public Nullable<double> quartoValor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hospedagem> hospedagems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reserva> reservas { get; set; }
    }
}
