//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeHotelaria
{
    using System;
    using System.Collections.Generic;
    
    public partial class servico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public servico()
        {
            this.servicosPrestados = new HashSet<servicosPrestado>();
        }
    
        public int servCodigo { get; set; }
        public string servDescricao { get; set; }
        public double servValor { get; set; }
        public int tipoCodigo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<servicosPrestado> servicosPrestados { get; set; }
        public virtual tipoServico tipoServico { get; set; }
    }
}
