//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeHotelaria
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipoPagamento
    {
        public int tipoCodigo { get; set; }
        public string tipoDescricao { get; set; }
    }
}
